In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Import necessary modules
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import roc_auc_score

In [4]:
data=pd.read_csv('/content/open_1h.csv')
data.head()

Unnamed: 0     open
0           0  5646332
1           1  5657077
2           2  5709340
3           3  5756905
4           4  5740132

In [3]:
data.drop(['Unnamed: 0'],axis=1,inplace=True)

In [4]:
data.head()

open
0  5646332
1  5657077
2  5709340
3  5756905
4  5740132

In [5]:
data.shape

(1500, 1)

In [6]:
data.isnull().sum()

open    0
dtype: int64

In [8]:
np.array(data['open'])

array([5646332, 5657077, 5709340, ..., 5534393, 5528664, 5542058])

In [20]:
def create_dataset(dataset, time_step=1):
  dataX, dataY = [], []
  for i in range(len(dataset)-time_step-1):
    a = dataset[i:(i+time_step)]   ###i=0,
    dataX.append(a)
    dataY.append(dataset[i + time_step])
  return np.array(dataX), np.array(dataY)

In [21]:
open=np.array(data['open'])
time_step=10
X,y=create_dataset((open),time_step)
X,y

(array([[5646332, 5657077, 5709340, ..., 5809545, 5860269, 5862728],
        [5657077, 5709340, 5756905, ..., 5860269, 5862728, 5866368],
        [5709340, 5756905, 5740132, ..., 5862728, 5866368, 5853103],
        ...,
        [5530983, 5505451, 5522211, ..., 5503524, 5485386, 5503698],
        [5505451, 5522211, 5507570, ..., 5485386, 5503698, 5520728],
        [5522211, 5507570, 5535291, ..., 5503698, 5520728, 5534393]]),
 array([5866368, 5853103, 5864950, ..., 5520728, 5534393, 5528664]))

In [22]:
size=int(len(X)*0.70)
X_train,X_test=X[:size],X[size:]
y_train,y_test=y[:size],y[size:]
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1042, 10), (447, 10), (1042,), (447,))

In [1]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

NameError: name 'X_train' is not defined